version: "2"

services: 
  motion:
    image: mosaiksoftware/debian-motion
    env_file: test.env
    tmpfs: /tmp
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"

